import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { CartProvider } from "./(public)/cart";
import { Toaster } from "react-hot-toast";
import Footer from "./(public)/landingPage/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // adjust as needed
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Moksha",
  description: "Generated by King",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-poppins">
        <CartProvider>
          <Navbar />
          {children}
          <Footer />
          <Toaster position="bottom-center" />
        </CartProvider>
      </body>
    </html>
  );
}
